In [14]:
import pandas as pd
df = pd.read_csv('pib.csv')

In [15]:
df

,Unnamed: 0,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.234335,3.493430,3.212471,1.229144,-23.940059,14.833692,10.607961,9.516360,6.810777,NaN
1,1,NaN,AFE,0.418605,7.937089,5.624317,4.650349,5.138153,4.827568,5.338803,...,2.292501,2.678863,2.706207,1.935593,-2.930764,4.452643,3.668029,1.941382,2.787931,3.743016
2,2,Afganistán,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,1.873193,NaN
3,3,NaN,AFW,1.869593,3.726016,7.038172,5.364580,4.105660,-1.512959,-8.966324,...,0.176172,2.302761,2.899954,3.283142,-3.718793,2.545473,4.477108,3.644591,4.596183,4.600100
4,4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.233077,-0.164689,-0.506698,-1.055234,-5.273491,1.090584,3.557492,1.320166,4.952679,3.133535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,260,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656,4.278499,4.067627,4.573097,3.592171
261,261,"Yemen, Rep. del",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-9.375124,-5.071796,0.752448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,262,Sudáfrica,ZAF,3.844734,6.177931,7.373709,7.939609,6.122798,4.438386,7.196523,...,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649,2.058137,0.806105,0.534844,1.114626
263,263,Zambia,ZMB,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,...,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048,3.757728
264,264,Zimbabwe,ZWE,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,...,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017,6.139263,5.350869,1.676495,8.106713

In [ ]:
#aqui podemos ver que tiene 265 filas y 68 columnas, podemos ver que las
columnas son el nombre del pais, el codigo del pais, y los años

In [20]:
df.head(25)

,Unnamed: 0,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.234335,3.493430,3.212471,1.229144,-23.940059,14.833692,10.607961,9.516360,6.810777,NaN
2,2,Afganistán,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,1.873193,NaN
4,4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.233077,-0.164689,-0.506698,-1.055234,-5.273491,1.090584,3.557492,1.320166,4.952679,3.133535
5,5,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.908936,3.283176,3.671419,2.062578,-3.313756,8.969576,4.826801,4.015417,4.045928,3.788938
6,6,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.709678,0.346072,1.588765,2.015548,-11.183940,8.286779,9.564612,2.583555,3.849161,3.868035
7,7,El mundo árabe,ARB,NaN,NaN,NaN,NaN,NaN,NaN,6.786332,...,3.572456,1.331270,2.670383,1.749492,-5.286414,4.431404,6.996676,1.648729,2.005218,3.677580
8,8,Emiratos Árabes Unidos,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.657901,-1.061371,1.537206,1.271291,-8.693434,4.552801,7.514524,4.301136,3.991812,NaN
9,9,Argentina,ARG,5.427843,-0.852022,-5.308197,10.130298,10.569433,-0.659726,3.191997,...,-2.080328,2.818503,-2.617396,-2.000861,-9.900485,10.441812,6.020745,-1.855788,-1.342931,4.367333
10,10,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.200000,7.500000,5.200000,7.600000,-7.200000,5.800000,12.600000,8.300000,5.900000,7.200000
11,11,Samoa Americana,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.679389,-6.987578,2.671119,-0.487805,4.411765,-0.782473,1.735016,NaN,NaN,NaN
12,12,Antigua y Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.120368,2.712727,6.712005,3.172222,-18.868777,8.172863,8.497763,3.865502,2.540442,4.998040
13,13,Australia,AUS,2.480857,1.296932,6.214376,6.977572,5.977505,2.381034,6.306899,...,2.755641,2.293310,2.874170,2.194017,-0.133532,2.006948,4.253046,3.583821,1.373408,1.350398
14,14,Austria,AUT,5.537979,2.648675,4.138268,6.124353,3.480175,5.642861,3.008047,...,2.117220,2.272250,2.484221,1.754976,-6.318255,4.923092,5.330964,-0.786244,-0.659090,0.615747
15,15,Azerbaiyán,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.063598,0.153615,1.500402,2.479809,-4.198961,5.616440,4.714680,1.354477,4.158068,1.449856
16,16,Burundi,BDI,-13.746135,9.063158,4.135407,6.273038,3.967226,4.612993,13.821519,...,3.200175,3.831858,5.342245,4.459342,0.306444,3.237075,2.317701,3.254769,4.112274,4.240105
17,17,Bélgica,BEL,4.978423,5.212003,4.351584,6.956685,3.560660,3.155895,3.868147,...,1.193503,1.474468,1.877968,2.442890,-4.792984,6.254457,4.024609,1.561255,1.097754,0.983118
18,18,Benin,BEN,3.141280,-3.426410,4.730028,6.650759,5.293863,3.575863,1.078399,...,3.339673,5.671562,6.697254,6.865687,3.848792,7.155452,6.252947,6.352777,7.453116,8.074085
19,19,Burkina Faso,BFA,4.043928,6.128799,-1.268016,2.282819,3.764545,0.537613,8.823315,...,5.957977,6.203489,6.604569,5.889205,2.010773,6.942525,1.626733,3.000274,4.833958,5.294618
20,20,Bangladesh,BGD,6.058161,5.453031,-0.455894,10.952789,1.606258,2.566812,-1.875864,...,7.113478,6.590250,7.319413,7.881915,3.448018,6.938679,7.099829,5.775112,4.223259,3.489907
21,21,Bulgaria,BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.026628,2.745927,2.330151,3.793320,-3.133235,7.828173,4.083864,1.681511,3.387090,3.096366
22,22,Bahrein,BHR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.814993,4.953835,2.052589,2.052878,-5.911363,4.350041,6.180161,3.878116,2.897105,3.481376
23,23,Bahamas,BHS,10.667097,10.451972,10.524055,10.501567,10.425596,9.071929,9.598114,...,-1.156508,3.371399,2.397955,-0.838586,-20.089366,17.586139,10.877901,3.048242,3.378666,NaN
24,24,Bosnia y Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.242258,3.244099,3.829004,2.885852,-3.015093,7.391643,4.226813,1.994394,3.226800,2.128619
25,25,Belarús,BLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.526446,2.532183,3.149198,1.446455,-0.672743,2.438862,-4.658396,4.126540,4.349996,1.300000
26,26,Belice,BLZ,4.892277,4.892652,4.956434,4.999880,4.930541,4.770845,4.913123,...,-0.018741,-1.833237,0.822069,4.256587,-13.522900,17.989924,9.250513,0.500128,3.504664,2.748317

In [26]:
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

In [27]:
df = df.dropna(subset=['Country Name'])

In [ ]:
aqui borramos los datos na ya que no correspondian a codigos de pais y borramos la columna unnamed: 0 
ya que no nos sirve

In [28]:
df

,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.234335,3.493430,3.212471,1.229144,-23.940059,14.833692,10.607961,9.516360,6.810777,NaN
2,Afganistán,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,1.873193,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.233077,-0.164689,-0.506698,-1.055234,-5.273491,1.090584,3.557492,1.320166,4.952679,3.133535
5,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.908936,3.283176,3.671419,2.062578,-3.313756,8.969576,4.826801,4.015417,4.045928,3.788938
6,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.709678,0.346072,1.588765,2.015548,-11.183940,8.286779,9.564612,2.583555,3.849161,3.868035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656,4.278499,4.067627,4.573097,3.592171
261,"Yemen, Rep. del",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-9.375124,-5.071796,0.752448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,Sudáfrica,ZAF,3.844734,6.177931,7.373709,7.939609,6.122798,4.438386,7.196523,4.153373,...,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649,2.058137,0.806105,0.534844,1.114626
263,Zambia,ZMB,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,1.248330,...,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048,3.757728
264,Zimbabwe,ZWE,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,1.970135,...,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017,6.139263,5.350869,1.676495,8.106713

In [29]:
ocde_codes = [
    'AUS', 'AUT', 'BEL', 'CAN', 'CHL', 'COL', 'CRI', 'CZE', 'DNK', 'EST',
    'FIN', 'FRA', 'DEU', 'GRC', 'HUN', 'ISL', 'IRL', 'ISR', 'ITA', 'JPN',
    'KOR', 'LVA', 'LTU', 'LUX', 'MEX', 'NLD', 'NZL', 'NOR', 'POL', 'PRT',
    'SVK', 'SVN', 'ESP', 'SWE', 'CHE', 'TUR', 'GBR', 'USA'
]

In [30]:
df_ocde = df[df['Country Code'].isin(ocde_codes)]

In [31]:
df_ocde

,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
13,Australia,AUS,2.480857,1.296932,6.214376,6.977572,5.977505,2.381034,6.306899,5.095130,...,2.755641,2.293310,2.874170,2.194017,-0.133532,2.006948,4.253046,3.583821,1.373408,1.350398
14,Austria,AUT,5.537979,2.648675,4.138268,6.124353,3.480175,5.642861,3.008047,4.472312,...,2.117220,2.272250,2.484221,1.754976,-6.318255,4.923092,5.330964,-0.786244,-0.659090,0.615747
17,Bélgica,BEL,4.978423,5.212003,4.351584,6.956685,3.560660,3.155895,3.868147,4.194129,...,1.193503,1.474468,1.877968,2.442890,-4.792984,6.254457,4.024609,1.561255,1.097754,0.983118
35,Canadá,CAN,3.163292,7.427837,5.297440,6.656000,6.317200,6.759690,3.065421,5.008274,...,1.038551,3.033835,2.742963,1.908432,-5.038233,5.950528,4.695420,1.953086,2.046266,1.742685
37,Suiza,CHE,5.681293,4.259047,5.327934,6.821165,3.821507,2.090844,3.365389,3.638506,...,1.911591,1.420346,3.327433,1.115322,-2.255258,6.176228,3.534303,0.825561,1.390334,1.300078
39,Chile,CHL,5.519611,3.930785,5.686672,2.461134,0.670839,11.463422,3.588111,3.573717,...,1.753039,1.357695,3.990029,0.644223,-6.139697,11.337403,2.063919,0.677025,2.805126,2.459255
45,Colombia,COL,5.089217,5.411890,3.286708,6.166941,3.600011,5.236736,4.134864,5.933118,...,2.087383,1.359361,2.564324,3.186855,-7.185914,10.801198,7.328277,0.841820,1.493307,2.642015
48,Costa Rica,CRI,1.879277,5.442391,6.898923,3.659048,8.190528,6.969319,5.650126,8.473304,...,4.204323,4.157699,2.852860,2.708139,-4.141593,8.218180,5.461195,4.791877,4.082924,4.560335
54,República Checa,CZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.580870,5.173565,2.830306,3.565777,-5.304880,4.029018,2.847171,0.047580,1.251311,2.580467
55,Alemania,DEU,4.298440,4.623471,2.735296,6.639470,5.244164,2.812181,-0.330256,5.668773,...,2.222222,2.797907,1.135696,0.977735,-4.131914,3.910000,1.809258,-0.869648,-0.495852,0.239578
58,Dinamarca,DNK,6.378832,5.666822,0.637021,9.269938,4.555255,2.740910,5.886231,5.852997,...,3.073045,3.056477,1.860007,1.711401,-1.780106,6.500254,0.443833,0.604588,3.477836,2.928433
70,España,ESP,11.838674,9.953438,9.596499,5.308510,6.253135,7.246060,4.340338,6.597020,...,2.915156,2.896042,2.395411,1.961179,-10.940071,6.683144,6.370317,2.460858,3.455254,2.824954
71,Estonia,EST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.093019,5.634672,3.699698,3.726649,-2.883808,8.254880,-1.226170,-2.744219,-0.090043,0.584308
74,Finlandia,FIN,7.604670,2.981946,3.285100,5.238686,5.302858,2.372822,2.168829,2.303290,...,2.571934,3.303370,1.192978,1.349738,-2.491036,2.676346,0.763042,-1.289735,0.374567,0.173445
76,Francia,FRA,4.946425,6.856265,6.103339,6.582807,4.838750,5.163543,4.801771,4.544018,...,0.860031,2.083615,1.645909,2.027446,-7.440646,6.882338,2.716763,1.439215,1.190468,0.840950
80,Reino Unido,GBR,2.701314,1.098696,4.859545,5.594811,2.130333,1.567450,2.775738,5.472693,...,2.206520,3.023222,1.551331,1.256299,-10.047897,8.543112,5.149704,0.271650,1.080277,1.388442
88,Grecia,GRC,13.203839,0.364812,11.844867,9.409677,10.768011,6.494501,5.669486,7.203718,...,-0.031795,1.473125,2.064672,2.277181,-9.196231,8.654498,5.521986,2.135911,2.086574,2.073069
100,Hungría,HUN,4.700000,6.100000,5.700000,4.700000,42.410414,7.400000,7.500000,4.900000,...,2.438641,4.124184,5.606138,5.077185,-4.338725,7.222916,4.152381,-0.817107,0.709071,0.509542
110,Irlanda,IRL,5.016169,3.216444,4.744634,3.785963,1.933449,0.893093,5.785704,8.243928,...,1.222717,10.108858,7.688659,4.972880,7.153695,16.258188,7.511139,-2.536374,2.599467,12.337599
113,Islandia,ISL,-0.074184,8.314774,10.281014,9.881914,7.296380,8.750659,-1.260301,-5.498282,...,6.218088,3.485067,4.660770,1.138212,-6.645878,5.180572,8.857299,5.032260,-1.282876,1.279462
114,Israel,ISR,11.203890,10.156117,10.695723,7.937187,8.997948,-0.079647,2.995026,16.241952,...,4.536019,4.343945,4.053500,3.578988,-1.802069,9.335347,6.364072,2.062725,0.953618,2.931150
115,Italia,ITA,8.207246,6.203650,5.609728,2.797702,3.268024,5.984794,7.178612,6.544555,...,1.236221,1.603700,0.826647,0.429163,-8.868221,8.931062,4.821177,0.922797,0.783039,0.539584
118,Japón,JPN,12.043536,8.908973,8.473642,11.676708,5.819708,10.638562,11.082142,12.882468,...,0.704986,1.623451,0.834144,-0.308497,-4.283279,3.564195,1.331648,0.720785,-0.240084,1.193113
125,"Corea, República de",KOR,6.920387,3.921758,9.009809,9.426714,7.313640,12.007993,9.151425,13.222886,...,3.171527,3.433192,3.176116,2.313802,-0.700242,4.612968,2.727565,1.583015,2.003611,1.007018
142,Lituania,LTU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.671922,4.612243,4.918368,4.677352,0.042816,6.394818,2.465320,0.739537,3.030195,2.920077
143,Luxemburgo,LUX,3.829981,1.358676,3.439112,7.865825,-0.734930,1.105899,0.216731,4.183877,...,4.978190,1.317119,1.611299,2.749321,-0.510052,6.929733,-1.097413,0.099437,0.358614,0.637878
144,Letonia,LVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.551686,3.398949,4.309713,0.675373,-3.469228,6.942542,1.908534,-0.941606,-0.037056,2.137869
153,México,MEX,5.000000,4.664415,8.106887,11.905481,7.100000,6.096139,5.854925,9.423279,...,1.772493,1.871729,1.972082,-0.392691,-8.354035,6.048483,3.709757,3.106796,1.350576,0.561683
175,Países Bajos,NLD,0.295547,6.843507,3.624622,8.274904,8.643095,2.741104,5.280015,6.416134,...,2.424281,2.781508,2.258732,2.300162,-3.867997,6.276836,5.007235,-0.598061,1.073831,1.784632
176,Noruega,NOR,6.273336,2.813945,3.785043,5.009651,5.285609,3.786513,6.256079,2.259876,...,1.291587,2.669645,1.110391,1.469708,-1.360557,4.143147,4.080398,0.352696,1.423721,1.085282
179,Nueva Zelandia,NZL,3.315650,3.080874,6.102117,6.103285,6.111732,6.248462,-4.589424,-0.048849,...,3.743525,3.315686,3.322197,2.323717,-0.240916,4.299160,3.345218,1.813895,-0.868722,0.462872
189,Polonia,POL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.031178,5.152458,6.245858,4.580458,-2.035569,6.927183,5.255457,0.249611,3.028416,3.572725
193,Portugal,PRT,5.534904,6.614447,5.873701,6.310748,7.468990,4.077909,7.544483,8.875510,...,2.004141,3.314720,2.946283,2.745684,-8.204632,5.558757,6.985841,3.099987,2.214592,1.864480
220,República Eslovaca,SVK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.947818,2.874733,4.062120,2.275899,-2.585512,5.655859,0.544592,2.112636,1.938674,0.807419
221,Eslovenia,SVN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.034415,5.174402,4.379083,3.505253,-4.085001,8.416865,2.668506,2.375833,1.731397,1.059930
222,Suecia,SWE,5.681293,4.259047,5.327934,6.821164,3.821508,2.090844,3.365389,3.638506,...,2.131179,1.882822,1.770255,2.608230,-1.933797,5.225864,1.255436,-0.204061,1.017796,1.543164
243,Turquía,TUR,1.156069,5.571429,9.066306,5.459057,2.823530,11.212815,4.732510,6.777996,...,3.323665,7.825857,3.468153,1.301624,1.803062,11.811094,5.441225,5.045124,3.327623,3.604625
250,Estados Unidos,USA,2.300000,6.100000,4.400000,5.800000,6.400000,6.500000,2.500000,4.800000,...,1.819451,2.457622,2.966505,2.583825,-2.081376,6.152022,2.524214,2.934363,2.793187,2.161382

In [32]:
df_ocde.to_csv("datos_ocde.csv", index=False)

In [33]:
import os
print(os.getcwd())

C:\Users\Matias